name: devour
description: A meme viewer.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter

  flutter_bloc: ^7.2.0
  flutter_cache_manager: ^3.1.2
  flutter_dotenv: ^5.0.2
  fpdart: ^0.0.10
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  logger: ^1.1.0
  lottie: ^1.2.1
  octo_image: ^1.0.0+1
  provider: ^6.0.0
  retrofit: ^2.0.1
  rive: ^0.7.28
  rxdart: ^0.27.2
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  synchronized: ^3.0.0
  url_launcher: ^6.0.10

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2
  json_serializable: ^5.0.0
  lint: ^1.7.2
  retrofit_generator: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/animations/space_coffee.riv
    - lib/assets/animations/space_loader.json
